# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WyBJaxnaE_orEzFyYdieuxBojS3Vl1xF

# Clinical Dataset

### Prior Filtering
"Modified Rankin Scale at 90 days": selection of instances with completed records (non-missing values)

"Diagnostic impression": selection of acute ischemic stroke (AIS)

## Setup, Data Ingestion, and Pipeline Utilities
"""

# Setup, Data Ingestion, and Pipeline Utilities
!pip install optuna catboost lightgbm xgboost fairlearn openpyxl tqdm -q

import os
import sys
import re
import json
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import optuna

# Scikit-Learn Ecosystem
import sklearn
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import SimpleImputer, KNNImputer, IterativeImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import roc_auc_score, f1_score, accuracy_score, confusion_matrix, brier_score_loss

# Classifiers
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from scipy import stats

# Global Configurations for Reproducibility and Output Formatting
np.random.seed(42)
sklearn.set_config(transform_output="pandas")
warnings.filterwarnings('ignore')
optuna.logging.set_verbosity(optuna.logging.WARNING)
plt.style.use('default')

# Directory Configuration (Modify ROOT_DIR to your environment)
ROOT_DIR = '/content/drive/MyDrive/avc/seed_refatoracao/code'
DATA_PATH = f"{ROOT_DIR}/dataset_cva.xlsx"
CLINICAL_OUT = f"{ROOT_DIR}/outputs_v2/clinical_stress_test"
CLINICAL_SINGLE_OUT = f"{ROOT_DIR}/outputs_v2/clinical_stress_test_single"
TABLES_DIR = f"{ROOT_DIR}/outputs_v2/results/clinical/tables"
FIGS_DIR = f"{ROOT_DIR}/outputs_v2/results/clinical/figures"

for path in [CLINICAL_OUT, CLINICAL_SINGLE_OUT, TABLES_DIR, FIGS_DIR]:
    os.makedirs(path, exist_ok=True)

# Utility Class to suppress verbose third-party outputs
class HiddenPrints:
    def __enter__(self):
        self._original_stdout = sys.stdout
        sys.stdout = open(os.devnull, 'w')
        return self
    def __exit__(self, exc_type, exc_val, exc_tb):
        sys.stdout.close()
        sys.stdout = self._original_stdout

# Data Ingestion and Preprocessing
df = pd.read_excel(DATA_PATH)
df.columns = [re.sub(r'[^a-z0-9_]+', '_', str(c).lower()).strip('_') for c in df.columns]

target_col = 'target_functional_independence_90d'
y = df[target_col].astype(int)
X = df.drop(columns=[target_col]).copy()

# Feature Sanity and Categorical Mapping
cat_cols = X.select_dtypes(include=['object', 'category']).columns.tolist()
num_cols = X.select_dtypes(exclude=['object', 'category']).columns.tolist()

def sanitize_feature_names(df_in):
    if isinstance(df_in, pd.DataFrame):
        df_in.columns = [re.sub(r'[^a-zA-Z0-9_]', '_', str(c)).strip('_') for c in df_in.columns]
        cols = pd.Series(df_in.columns)
        for dup in cols[cols.duplicated()].unique():
            cols[cols[cols == dup].index.values.tolist()] = [dup + '_' + str(i) if i != 0 else dup for i in range(sum(cols == dup))]
        df_in.columns = cols
    return df_in

class CorrelationDropper(BaseEstimator, TransformerMixin):
    def __init__(self, threshold=0.85):
        self.threshold = threshold
        self.to_drop_ = []
    def fit(self, X, y=None):
        if not isinstance(X, pd.DataFrame): X = pd.DataFrame(X)
        corr_matrix = X.corr(numeric_only=True).abs()
        upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
        self.to_drop_ = [column for column in upper.columns if any(upper[column] > self.threshold)]
        return self
    def transform(self, X, y=None):
        if not isinstance(X, pd.DataFrame): X = pd.DataFrame(X)
        return X.drop(columns=self.to_drop_, errors='ignore')

def get_classic_preprocessor(imp_name, current_seed):
    if imp_name == 'MICE': imp = IterativeImputer(random_state=current_seed, max_iter=10)
    elif imp_name == 'KNN': imp = KNNImputer(n_neighbors=5)
    else: imp = SimpleImputer(strategy='median')

    num_pipe = Pipeline([('imp', imp), ('scaler', StandardScaler())])
    cat_pipe = Pipeline([('imp', SimpleImputer(strategy='constant', fill_value='Unknown')),
                         ('ohe', OneHotEncoder(handle_unknown='ignore', sparse_output=False))])
    return ColumnTransformer([('num', num_pipe, num_cols), ('cat', cat_pipe, cat_cols)])

def get_native_ood(X_tr, X_te):
    X_tr_nat, X_te_nat = X_tr.copy(), X_te.copy()
    X_tr_nat[cat_cols] = X_tr_nat[cat_cols].fillna('Unknown')
    X_te_nat[cat_cols] = X_te_nat[cat_cols].fillna('Unknown')
    medians = X_tr_nat[num_cols].median()
    X_tr_nat[num_cols] = X_tr_nat[num_cols].fillna(medians)
    X_te_nat[num_cols] = X_te_nat[num_cols].fillna(medians)

    for c in cat_cols:
        known = list(X_tr_nat[c].unique())
        X_te_nat[c] = X_te_nat[c].apply(lambda x: x if x in known else 'Unknown')
        ctype = pd.CategoricalDtype(categories=list(set(known + ['Unknown'])), ordered=False)
        X_tr_nat[c], X_te_nat[c] = X_tr_nat[c].astype(ctype), X_te_nat[c].astype(ctype)

    return sanitize_feature_names(X_tr_nat), sanitize_feature_names(X_te_nat)

def map_features_to_raw(selected_encoded_features, original_feature_names):
    raw_detected = set()
    for enc_feat in selected_encoded_features:
        for raw_col in original_feature_names:
            if enc_feat.startswith(raw_col) or enc_feat.startswith(f"cat__{raw_col}") or enc_feat.startswith(f"num__{raw_col}"):
                raw_detected.add(raw_col)
                break
    return list(raw_detected)

def get_comprehensive_metrics(y_t, y_p, y_prob, prefix=''):
    tn, fp, fn, tp = confusion_matrix(y_t, y_p, labels=[0,1]).ravel()
    return {
        f'{prefix}AUC': roc_auc_score(y_t, y_prob) if y_prob is not None else np.nan,
        f'{prefix}Brier_Score': brier_score_loss(y_t, y_prob) if y_prob is not None else np.nan,
        f'{prefix}F1': f1_score(y_t, y_p) if np.sum(y_p) > 0 else 0.0,
        f'{prefix}Sensitivity': tp / (tp + fn + 1e-9),
        f'{prefix}Specificity': tn / (tn + fp + 1e-9),
        f'{prefix}Accuracy': accuracy_score(y_t, y_p)
    }

# Algorithm Configuration Spaces
experiments_classic = [
    ('LR', 'Median'), ('LR', 'KNN'), ('LR', 'MICE'),
    ('RF', 'Median'), ('RF', 'KNN'), ('RF', 'MICE'),
    ('SVM', 'Median'), ('SVM', 'KNN'), ('SVM', 'MICE'),
    ('XGB', 'Median'), ('XGB', 'KNN'), ('XGB', 'MICE'),
    ('LGBM', 'Median'), ('LGBM', 'KNN'), ('LGBM', 'MICE'),
    ('CATB', 'Median'), ('CATB', 'KNN'), ('CATB', 'MICE')
]

experiments_native = [
    ('CATB_Native', 'Native_OOD'),
    ('LGBM_Native', 'Native_OOD'),
    ('XGB_Native', 'Native_OOD')
]

# Hyperparameter Optimization Engine
def optimize_algorithm(model_name, imp_name, X_tr, y_tr, current_seed, is_native=False, use_cv=True):
    cv_inner = StratifiedKFold(n_splits=5, shuffle=True, random_state=current_seed)

    if not is_native:
        pipeline_prep = Pipeline([('prep', get_classic_preprocessor(imp_name, current_seed)), ('corr_drop', CorrelationDropper(threshold=0.85))])
        X_opt = sanitize_feature_names(pipeline_prep.fit_transform(X_tr))
    else:
        X_opt = X_tr

    if not use_cv:
        X_sub_tr, X_val, y_sub_tr, y_val = train_test_split(X_opt, y_tr, test_size=0.25, random_state=current_seed, stratify=y_tr)

    def objective(trial):
        try:
            if is_native:
                if model_name == 'CATB_Native': clf = CatBoostClassifier(iterations=trial.suggest_categorical('iterations', [30, 50]), depth=trial.suggest_categorical('depth', [2, 3]), learning_rate=trial.suggest_categorical('learning_rate', [0.01, 0.05]), l2_leaf_reg=trial.suggest_categorical('l2_leaf_reg', [1.0, 3.0, 5.0]), random_state=current_seed, verbose=False, cat_features=cat_cols, auto_class_weights='Balanced')
                elif model_name == 'LGBM_Native': clf = LGBMClassifier(n_estimators=trial.suggest_categorical('n_estimators', [30, 50]), max_depth=trial.suggest_categorical('max_depth', [2, 3]), learning_rate=trial.suggest_categorical('learning_rate', [0.01, 0.05]), num_leaves=trial.suggest_categorical('num_leaves', [4, 7]), min_child_samples=trial.suggest_categorical('min_child_samples', [2, 5]), verbose=-1, random_state=current_seed, is_unbalance=True)
                elif model_name == 'XGB_Native': clf = XGBClassifier(n_estimators=trial.suggest_categorical('n_estimators', [30, 50]), max_depth=trial.suggest_categorical('max_depth', [2, 3]), learning_rate=trial.suggest_categorical('learning_rate', [0.01, 0.05]), subsample=trial.suggest_categorical('subsample', [0.8, 1.0]), colsample_bytree=trial.suggest_categorical('colsample_bytree', [0.8, 1.0]), enable_categorical=True, tree_method='hist', random_state=current_seed)

                if use_cv:
                    scores = []
                    for tr_idx, val_idx in cv_inner.split(X_opt, y_tr):
                        X_f_tr, X_f_val = X_opt.iloc[tr_idx], X_opt.iloc[val_idx]
                        y_f_tr, y_f_val = y_tr.iloc[tr_idx], y_tr.iloc[val_idx]
                        with HiddenPrints(): clf.fit(X_f_tr, y_f_tr)
                        scores.append(roc_auc_score(y_f_val, clf.predict_proba(X_f_val)[:, 1]))
                    return np.mean(scores)
                else:
                    with HiddenPrints(): clf.fit(X_sub_tr, y_sub_tr)
                    return roc_auc_score(y_val, clf.predict_proba(X_val)[:, 1])
            else:
                max_avail = X_opt.shape[1]
                n_features = trial.suggest_int('n_features', min(5, max_avail), max_avail)

                if model_name == 'LR': clf = LogisticRegression(penalty=trial.suggest_categorical('penalty', ['l1', 'l2']), C=trial.suggest_categorical('C', [0.1, 1.0, 5.0]), solver='liblinear', class_weight='balanced', random_state=current_seed)
                elif model_name == 'RF': clf = RandomForestClassifier(n_estimators=trial.suggest_categorical('n_estimators', [30, 50]), max_depth=trial.suggest_categorical('max_depth', [2, 3]), min_samples_split=trial.suggest_categorical('min_samples_split', [2, 5]), class_weight='balanced', random_state=current_seed)
                elif model_name == 'SVM': clf = SVC(C=trial.suggest_categorical('C', [0.1, 1.0, 5.0]), kernel=trial.suggest_categorical('kernel', ['linear', 'rbf']), probability=True, class_weight='balanced', random_state=current_seed)
                elif model_name == 'XGB': clf = XGBClassifier(n_estimators=trial.suggest_categorical('n_estimators', [30, 50]), max_depth=trial.suggest_categorical('max_depth', [2, 3]), learning_rate=trial.suggest_categorical('learning_rate', [0.01, 0.05]), subsample=trial.suggest_categorical('subsample', [0.8, 1.0]), eval_metric='logloss', random_state=current_seed)
                elif model_name == 'LGBM': clf = LGBMClassifier(n_estimators=trial.suggest_categorical('n_estimators', [30, 50]), max_depth=trial.suggest_categorical('max_depth', [2, 3]), learning_rate=trial.suggest_categorical('learning_rate', [0.01, 0.05]), num_leaves=trial.suggest_categorical('num_leaves', [4, 7]), min_child_samples=trial.suggest_categorical('min_child_samples', [2, 5]), verbose=-1, is_unbalance=True, random_state=current_seed)
                elif model_name == 'CATB': clf = CatBoostClassifier(iterations=trial.suggest_categorical('iterations', [30, 50]), depth=trial.suggest_categorical('depth', [2, 3]), learning_rate=trial.suggest_categorical('learning_rate', [0.01, 0.05]), l2_leaf_reg=trial.suggest_categorical('l2_leaf_reg', [1.0, 3.0, 5.0]), random_state=current_seed, verbose=False, auto_class_weights='Balanced')

                selector = SelectFromModel(RandomForestClassifier(n_estimators=50, max_depth=3, class_weight='balanced', random_state=current_seed), max_features=n_features, threshold=-np.inf)

                if use_cv:
                    pipe_eval = Pipeline([('feat_sel', selector), ('clf', clf)])
                    with HiddenPrints(): return np.mean(cross_val_score(pipe_eval, X_opt, y_tr, cv=cv_inner, scoring='roc_auc'))
                else:
                    X_sub_tr_f = selector.fit_transform(X_sub_tr, y_sub_tr)
                    X_val_f = selector.transform(X_val)
                    with HiddenPrints(): clf.fit(X_sub_tr_f, y_sub_tr)
                    return roc_auc_score(y_val, clf.predict_proba(X_val_f)[:, 1])

        except Exception: return 0.5

    study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=current_seed))
    study.optimize(objective, n_trials=20)
    try: return study.best_params, study.best_value
    except ValueError: return None, None

"""## Predictions - Seeds 42, 84, 168"""

# Seeds 42, 84, 168 (Table 1 Context)
TARGET_SEEDS = [42, 84, 168]
TARGET_CSV = f"{CLINICAL_OUT}/Targeted_Seeds_Evaluation.csv"

def execute_pipeline_for_seed(current_seed, use_cv=True):
    seed_results = []
    original_cols = X.columns.tolist()
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=current_seed, stratify=y)

    missing_cols = X_train.columns[X_train.isnull().any()].tolist()
    for col in missing_cols:
        X_train[f"{col}_missing_flag"] = X_train[col].isnull().astype(int)
        X_test[f"{col}_missing_flag"] = X_test[col].isnull().astype(int)

    X_train_nat, X_test_nat = get_native_ood(X_train, X_test)

    # Classic Pipeline
    for model_name, imp_name in experiments_classic:
        params, cv_auc = optimize_algorithm(model_name, imp_name, X_train, y_train, current_seed, is_native=False, use_cv=use_cv)
        if not params: continue

        n_features = params.get('n_features', X_train.shape[1])
        clf_params = {k: v for k, v in params.items() if k != 'n_features'}

        pipe_prep = Pipeline([('prep', get_classic_preprocessor(imp_name, current_seed)), ('corr_drop', CorrelationDropper(threshold=0.85))])
        X_tr_p = sanitize_feature_names(pipe_prep.fit_transform(X_train))
        X_te_p = sanitize_feature_names(pipe_prep.transform(X_test))

        selector = SelectFromModel(RandomForestClassifier(n_estimators=50, max_depth=3, class_weight='balanced', random_state=current_seed), max_features=n_features, threshold=-np.inf)
        X_tr_f = selector.fit_transform(X_tr_p, y_train)
        X_te_f = selector.transform(X_te_p)

        raw_features_list = map_features_to_raw(X_tr_p.columns[selector.get_support()].tolist(), original_cols)

        if model_name == 'LR': clf = LogisticRegression(**clf_params, solver='liblinear', class_weight='balanced', random_state=current_seed)
        elif model_name == 'RF': clf = RandomForestClassifier(**clf_params, class_weight='balanced', random_state=current_seed)
        elif model_name == 'SVM': clf = SVC(**clf_params, probability=True, class_weight='balanced', random_state=current_seed)
        elif model_name == 'XGB': clf = XGBClassifier(**clf_params, eval_metric='logloss', random_state=current_seed)
        elif model_name == 'LGBM': clf = LGBMClassifier(**clf_params, verbose=-1, is_unbalance=True, random_state=current_seed)
        elif model_name == 'CATB': clf = CatBoostClassifier(**clf_params, random_state=current_seed, verbose=False, auto_class_weights='Balanced')

        try:
            with HiddenPrints(): clf.fit(X_tr_f, y_train)
            y_pred_te, y_prob_te = clf.predict(X_te_f), clf.predict_proba(X_te_f)[:, 1]
            row = {'Seed': current_seed, 'Algorithm': model_name, 'Imputation': imp_name,
                   'Raw_Features_Count': len(raw_features_list),
                   'Selected_Raw_Features': "; ".join(raw_features_list),
                   'CV_AUC_Score': cv_auc}            row.update(get_comprehensive_metrics(y_test, y_pred_te, y_prob_te, 'Test_'))
            seed_results.append(row)
        except Exception: pass

    # Native Pipeline
    for model_name, imp_name in experiments_native:
        params, cv_auc = optimize_algorithm(model_name, imp_name, X_train_nat, y_train, current_seed, is_native=True, use_cv=use_cv)
        if not params: continue

        if model_name == 'CATB_Native': clf = CatBoostClassifier(**params, random_state=current_seed, verbose=False, cat_features=cat_cols, auto_class_weights='Balanced')
        elif model_name == 'LGBM_Native': clf = LGBMClassifier(**params, verbose=-1, random_state=current_seed, is_unbalance=True)
        elif model_name == 'XGB_Native': clf = XGBClassifier(**params, enable_categorical=True, tree_method='hist', random_state=current_seed)

        try:
            with HiddenPrints(): clf.fit(X_train_nat, y_train)
            y_pred_te, y_prob_te = clf.predict(X_test_nat), clf.predict_proba(X_test_nat)[:, 1]
            all_raw = map_features_to_raw(X_train_nat.columns.tolist(), original_cols)
            row = {'Seed': current_seed, 'Algorithm': model_name, 'Imputation': imp_name,
                   'Raw_Features_Count': len(all_raw),
                   'Selected_Raw_Features': "; ".join(all_raw),
                   'CV_AUC_Score': cv_auc}
            row.update(get_comprehensive_metrics(y_test, y_pred_te, y_prob_te, 'Test_'))
            seed_results.append(row)
        except Exception: pass

    return seed_results

from tqdm.auto import tqdm
print("Executing Targeted Validation (Seeds: 42, 84, 168)...")
all_targeted_results = []
for seed in tqdm(TARGET_SEEDS):
    all_targeted_results.extend(execute_pipeline_for_seed(seed, use_cv=True))

pd.DataFrame(all_targeted_results).to_csv(TARGET_CSV, sep=';', index=False)

"""## Exhaustive Stochastic Validation"""

# Exhaustive Stochastic Validation (100 Seeds)
START_SEED = 0
END_SEED = 100
MASTER_CV_CSV = f"{CLINICAL_OUT}/Comprehensive_MultiSeed_Master_Log.csv"
MASTER_NOCV_CSV = f"{CLINICAL_SINGLE_OUT}/Comprehensive_MultiSeed_Single_Optuna_Master_Log.csv"

completed_cv = set(pd.read_csv(MASTER_CV_CSV, sep=';')['Seed'].unique()) if os.path.exists(MASTER_CV_CSV) else set()
completed_nocv = set(pd.read_csv(MASTER_NOCV_CSV, sep=';')['Seed'].unique()) if os.path.exists(MASTER_NOCV_CSV) else set()

pending_seeds = [s for s in range(START_SEED, END_SEED) if s not in completed_cv or s not in completed_nocv]

if pending_seeds:
    print(f"Executing Exhaustive Stochastic Validation ({len(pending_seeds)} seeds remaining)...")
    for current_seed in tqdm(pending_seeds):

        # Branch 1: Internal Cross-Validation (Main methodology)
        if current_seed not in completed_cv:
            res_cv = execute_pipeline_for_seed(current_seed, use_cv=True)
            if res_cv:
                df_cv = pd.DataFrame(res_cv)
                df_cv.to_csv(MASTER_CV_CSV, mode='a', header=not os.path.exists(MASTER_CV_CSV), index=False, sep=';')

        # Branch 2: Single Internal Split (No CV - Supplementary methodology)
        if current_seed not in completed_nocv:
            res_nocv = execute_pipeline_for_seed(current_seed, use_cv=False)
            if res_nocv:
                df_nocv = pd.DataFrame(res_nocv)
                df_nocv.to_csv(MASTER_NOCV_CSV, mode='a', header=not os.path.exists(MASTER_NOCV_CSV), index=False, sep=';')
else:
    print("All 100 seeds have been successfully evaluated.")

"""## Statistical Analysis and Artifact Generation"""

# 4. Statistical Analysis and Artifact Generation
import itertools
print("[*] Generating publication-ready tables, figures, and statistical tests...")

df_cv = pd.read_csv(MASTER_CV_CSV, sep=';')
df_cv['Model_Key'] = df_cv['Algorithm'] + " (" + df_cv['Imputation'] + ")"
metric_cols = ['Test_AUC', 'Test_Brier_Score', 'Test_F1', 'Test_Sensitivity', 'Test_Specificity', 'Raw_Features_Count']
for c in metric_cols: df_cv[c] = pd.to_numeric(df_cv[c], errors='coerce')
df_cv = df_cv.dropna(subset=['Test_AUC'])

# Table 1: Contrasting Partitions (Seeds 168, 42, 84)
table1_parts = []
for s_val, s_label in [(168, "Optimistic (Seed 168)"), (42, "Benchmark (Seed 42)"), (84, "Pessimistic (Seed 84)")]:
    sub = df_cv[df_cv['Seed'] == s_val].sort_values('Test_AUC', ascending=False).head(5).copy()
    sub['Partition'] = s_label
    table1_parts.append(sub)

df_t1 = pd.concat(table1_parts, ignore_index=True)[['Partition', 'Model_Key', 'Test_AUC', 'Test_F1', 'Test_Sensitivity', 'Test_Specificity', 'Raw_Features_Count']]
df_t1.columns = ['Partition', 'Algorithm (Imputation)', 'Test AUC', 'Test F1', 'Test Sens.', 'Test Spec.', 'Clinical Predictors']
for c in ['Test AUC', 'Test F1', 'Test Sens.', 'Test Spec.']: df_t1[c] = df_t1[c].apply(lambda x: f"{x:.3f}")
df_t1.to_excel(f"{TABLES_DIR}/Table_1_Partition_Contrast.xlsx", index=False)

# Statistical Testing (Omnibus & Pairwise)
pivot_pipe = df_cv.pivot(index='Seed', columns='Model_Key', values='Test_AUC').dropna()
chi2_p, pval_p = stats.friedmanchisquare(*[pivot_pipe[c].values for c in pivot_pipe.columns])
print(f"Omnibus Friedman test (21 configurations): Chi2 = {chi2_p:.2f}, p = {pval_p:.4e}")

stats_all = df_cv.groupby('Model_Key')[metric_cols].agg(['mean', 'std'])
stats_all = stats_all.sort_values(by=('Test_AUC', 'mean'), ascending=False)
lead_pipe = stats_all.index[0]

comp_results = []
for comp in stats_all.index[1:5]:
    _, p_val = stats.wilcoxon(pivot_pipe[lead_pipe], pivot_pipe[comp])
    comp_results.append(p_val)

# Holm-Bonferroni correction
sorted_idx = np.argsort(comp_results)
adj_p = np.empty(len(comp_results))
current_max = 0.0
for i in range(len(comp_results)):
    adj = (len(comp_results) - i) * comp_results[sorted_idx[i]]
    current_max = max(current_max, adj)
    adj_p[sorted_idx[i]] = min(current_max, 1.0)

print(f"\nPairwise Wilcoxon vs {lead_pipe} (Holm-Bonferroni Adjusted):")
for i, comp in enumerate(stats_all.index[1:5]):
    print(f" - vs {comp}: adj_p = {adj_p[i]:.4e}")

# Table S1 (formerly S2): Aggregated Metrics
table_s1_dict = {'Algorithm (Imputation)': stats_all.index}
for m, name in zip(['Test_AUC', 'Test_Brier_Score', 'Test_F1', 'Test_Sensitivity', 'Test_Specificity'], ['AUC', 'Brier', 'F1', 'Sens', 'Spec']):
    low, high = df_cv.groupby('Model_Key')[m].quantile(0.025), df_cv.groupby('Model_Key')[m].quantile(0.975)
    table_s1_dict[f'{name} Mean (SD)'] = [f"{r[(m, 'mean')]:.3f} (±{r[(m, 'std')]:.3f})" for _, r in stats_all.iterrows()]
    table_s1_dict[f'{name} 95% Range'] = [f"[{l:.3f}, {h:.3f}]" for l, h in zip(low[stats_all.index], high[stats_all.index])]

df_t_s1 = pd.DataFrame(table_s1_dict)
df_t_s1.to_excel(f"{TABLES_DIR}/Table_S1_Aggregated_Metrics.xlsx", index=False)

# Figure 1: Convergence and Rank Instability
top_5_pipes = stats_all.index[:5].tolist()
df_best = df_cv[df_cv['Model_Key'] == lead_pipe].sort_values('Seed')
auc_vals = df_best['Test_AUC'].values
k_range = np.arange(5, len(auc_vals) + 1)
run_mean = [np.mean(auc_vals[:k]) for k in k_range]
run_sem = [np.std(auc_vals[:k], ddof=1) / np.sqrt(k) for k in k_range]

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))
ax1.plot(k_range, run_mean, color='#1f78b4', lw=2, label='Cumulative Mean AUC')
ax1.fill_between(k_range, np.array(run_mean) - 1.96*np.array(run_sem), np.array(run_mean) + 1.96*np.array(run_sem), color='#1f78b4', alpha=0.2)
ax1_twin = ax1.twinx()
ax1_twin.plot(k_range, run_sem, color='#e31a1c', ls='--', lw=2)
ax1_twin.axhline(0.015, color='gray', ls=':')
ax1.set_title(f"(a)\nClinical Precision Convergence ({lead_pipe})", fontweight='bold')
ax1.set_xlabel("Number of Random Seeds")
ax1.set_ylabel("Running Mean Test AUC-ROC")

df_cv['Seed_Rank'] = df_cv.groupby('Seed')['Test_AUC'].rank(ascending=False, method='min')
sns.boxplot(x='Model_Key', y='Seed_Rank', data=df_cv[df_cv['Model_Key'].isin(top_5_pipes)], order=top_5_pipes, color='#f7f7f7', ax=ax2, showfliers=False)
sns.stripplot(x='Model_Key', y='Seed_Rank', data=df_cv[df_cv['Model_Key'].isin(top_5_pipes)], order=top_5_pipes, color='#2b2b2b', alpha=0.4, jitter=0.2, ax=ax2)
ax2.invert_yaxis()
ax2.set_title("(b)\nAlgorithm Rank Instability", fontweight='bold')
ax2.set_xlabel("Pipeline Configuration")
ax2.set_ylabel("Achieved Rank in Partition")
plt.tight_layout()
plt.savefig(f"{FIGS_DIR}/Figure_1_Clinical_Stability.png", dpi=300, bbox_inches='tight')
plt.close()

# Figure S1: Feature Stability & Jaccard Index
if 'Selected_Raw_Features' in df_cv.columns:
    fig_s1, (ax_s1a, ax_s1b) = plt.subplots(1, 2, figsize=(16, 6))

    # Panel A: Feature Frequency
    all_feats = df_cv['Selected_Raw_Features'].dropna().str.split('; ').explode()
    feat_freq = (all_feats.value_counts().head(20) / len(df_cv)) * 100
    sns.barplot(x=feat_freq.values, y=feat_freq.index, color='#4682b4', ax=ax_s1a)
    ax_s1a.set_title("(a)\nTop 20 Clinical Predictors Selection Frequency", fontweight='bold')
    ax_s1a.set_xlabel("Selection Frequency Across Partitions (%)")

    # Panel B: Jaccard
    features_by_seed = df_best.set_index('Seed')['Selected_Raw_Features'].dropna().str.split('; ').apply(set).to_dict()
    jaccard_scores = []
    for s1, s2 in itertools.combinations(features_by_seed.keys(), 2):
        set1, set2 = features_by_seed[s1], features_by_seed[s2]
        if set1 or set2: jaccard_scores.append(len(set1.intersection(set2)) / len(set1.union(set2)))

    mean_j = np.mean(jaccard_scores)
    sns.histplot(jaccard_scores, bins=15, kde=True, color='#2ca02c', ax=ax_s1b)
    ax_s1b.axvline(mean_j, color='red', linestyle='--', label=f'Mean = {mean_j:.3f}')
    ax_s1b.set_title(f"(b)\nFeature Selection Jaccard Stability ({lead_pipe})", fontweight='bold')
    ax_s1b.set_xlabel("Pairwise Jaccard Similarity Index (0 = Disjoint, 1 = Identical)")
    ax_s1b.set_ylabel("Frequency of Seed Pairs")
    ax_s1b.legend()
    plt.tight_layout()
    plt.savefig(f"{FIGS_DIR}/Figure_S1_Feature_Stability.png", dpi=300, bbox_inches='tight')
    plt.close()

# Figure S2: Single Validation (No CV) Performance
if os.path.exists(MASTER_NOCV_CSV):
    df_nocv = pd.read_csv(MASTER_NOCV_CSV, sep=';')
    df_nocv['Model_Key'] = df_nocv['Algorithm'] + " (" + df_nocv['Imputation'] + ")"
    df_nocv['Test_AUC'] = pd.to_numeric(df_nocv['Test_AUC'], errors='coerce')
    df_nocv = df_nocv.dropna(subset=['Test_AUC'])

    fig_s2, (ax_s2a, ax_s2b, ax_s2c) = plt.subplots(1, 3, figsize=(20, 6))

    # Panel A: Convergence (No CV)
    nocv_best = df_nocv[df_nocv['Model_Key'] == lead_pipe].sort_values('Seed')['Test_AUC'].values
    k_rng_nocv = np.arange(5, len(nocv_best) + 1)
    r_mean_nocv = [np.mean(nocv_best[:k]) for k in k_rng_nocv]
    r_sem_nocv = [np.std(nocv_best[:k], ddof=1) / np.sqrt(k) for k in k_rng_nocv]

    ax_s2a.plot(k_rng_nocv, r_mean_nocv, color='#1f78b4', lw=2)
    ax_s2a.fill_between(k_rng_nocv, np.array(r_mean_nocv) - 1.96*np.array(r_sem_nocv), np.array(r_mean_nocv) + 1.96*np.array(r_sem_nocv), color='#1f78b4', alpha=0.2)
    ax_s2a.set_title(f"(a)\nSeed Precision Convergence ({lead_pipe} - Without CV)", fontweight='bold')
    ax_s2a.set_xlabel("Number of Random Seeds")
    ax_s2a.set_ylabel("Running Mean Test AUC-ROC")

    # Panel B: Rank Instability (No CV)
    df_nocv['Seed_Rank'] = df_nocv.groupby('Seed')['Test_AUC'].rank(ascending=False, method='min')
    sns.boxplot(x='Model_Key', y='Seed_Rank', data=df_nocv[df_nocv['Model_Key'].isin(top_5_pipes)], order=top_5_pipes, color='#f7f7f7', ax=ax_s2b, showfliers=False)
    sns.stripplot(x='Model_Key', y='Seed_Rank', data=df_nocv[df_nocv['Model_Key'].isin(top_5_pipes)], order=top_5_pipes, color='#2b2b2b', alpha=0.4, jitter=0.2, ax=ax_s2b)
    ax_s2b.invert_yaxis()
    ax_s2b.set_title("(b)\nAlgorithm Rank Instability under Single Validation", fontweight='bold')
    ax_s2b.set_xlabel("Pipeline Configuration")
    ax_s2b.set_ylabel("Achieved Rank")
    ax_s2b.tick_params(axis='x', rotation=45)

    # Panel C: Dispersion KDE
    for pipe_name in top_5_pipes[:3]:
        sns.kdeplot(data=df_nocv[df_nocv['Model_Key'] == pipe_name]['Test_AUC'], lw=2, label=pipe_name, ax=ax_s2c)
    ax_s2c.set_title("(c)\nAlgorithm Stability under Single Validation Paradigm", fontweight='bold')
    ax_s2c.set_xlabel("Test Set AUC-ROC")
    ax_s2c.legend()

    plt.tight_layout()
    plt.savefig(f"{FIGS_DIR}/Figure_S2_Single_Validation.png", dpi=300, bbox_inches='tight')
    plt.close()

print("\n[*] Clinical Artifact generation complete. Files saved to output directories.")

"""# In Silico - Simulations

## In Silico Setup, Utilities, and Simulation Engine
"""

# In Silico Setup, Utilities & Simulation Engine
import os
import itertools
import numpy as np
import pandas as pd
from tqdm.auto import tqdm
import matplotlib.pyplot as plt
import seaborn as sns

# Scikit-Learn Ecosystem for Simulation
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split, StratifiedKFold, RepeatedStratifiedKFold, cross_val_predict, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score, brier_score_loss, f1_score, confusion_matrix
from xgboost import XGBClassifier

# Global Configurations
np.random.seed(42)
import warnings
warnings.filterwarnings('ignore')

# Directory Configuration (Using outputs_v2 as requested)
ROOT_DIR = '/content/drive/MyDrive/avc/seed_refatoracao/code'
SIM_DIR = f"{ROOT_DIR}/outputs_v2/simulation"
SIM_DATA_DIR = f"{SIM_DIR}/data"
SIM_FIGS_DIR = f"{SIM_DIR}/figures"
SIM_TABLES_DIR = f"{SIM_DIR}/tables"

for path in [SIM_DATA_DIR, SIM_FIGS_DIR, SIM_TABLES_DIR]:
    os.makedirs(path, exist_ok=True)

# Core Simulation Engine Functions
def apply_clinical_boundary_noise(X_data, y_data, noise_level=0.15):
    """Simulates clinical diagnostic ambiguity by flipping labels close to the decision boundary."""
    clf_probe = LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42)
    clf_probe.fit(X_data, y_data)
    probs = clf_probe.predict_proba(X_data)[:, 1]

    boundary_distance = np.abs(probs - 0.5)
    n_flip = int(len(y_data) * noise_level)
    ambiguous_idx = np.argsort(boundary_distance)[:n_flip]

    y_noisy = y_data.copy()
    y_noisy[ambiguous_idx] = 1 - y_noisy[ambiguous_idx]
    return y_noisy

def compute_metrics_bundle(y_true, y_prob):
    """Calculates comprehensive classification, calibration, and discrimination metrics."""
    y_pred = (y_prob >= 0.5).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()

    try: auc_val = roc_auc_score(y_true, y_prob) if len(np.unique(y_true)) > 1 else np.nan
    except Exception: auc_val = np.nan

    return {
        'AUC': auc_val,
        'Brier': brier_score_loss(y_true, y_prob),
        'F1': f1_score(y_true, y_pred, zero_division=0),
        'Sens': tp / (tp + fn + 1e-9),
        'Spec': tn / (tn + fp + 1e-9)
    }

def get_classifier(model_name, seed):
    """Standardized classifiers across different learning paradigms to isolate variance."""
    if model_name == 'LogisticRegression':
        return LogisticRegression(max_iter=1000, class_weight='balanced', random_state=seed)
    elif model_name == 'XGBoost':
        return XGBClassifier(n_estimators=100, max_depth=3, learning_rate=0.05, eval_metric='logloss', random_state=seed)
    else:
        return RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=seed)

SIM_SEEDS = 100
print(f"[*] In Silico Environment Ready. Output directory: {SIM_DIR}")

"""## Dense Variance Funnel Simulation"""

# Dense Variance Funnel Simulation (Fine-Grained Sample Size Decay)
dense_csv_path = f"{SIM_DATA_DIR}/Dense_Funnel_Simulation_Results.csv"
dense_sample_sizes = list(range(50, 525, 25))

print(f"[*] Initializing Dense Variance Funnel Simulation (19 Sample Sizes, {SIM_SEEDS} Repetitions)...")

# Generate synthetic universe under clinical anchor parameters (p=15, 80/20, boundary noise)
X_univ, y_univ = make_classification(
    n_samples=5000, n_features=15, n_informative=9, n_redundant=3, n_clusters_per_class=2,
    flip_y=0.0, weights=[0.8, 0.2], class_sep=0.8, random_state=42
)
y_univ = apply_clinical_boundary_noise(X_univ, y_univ, noise_level=0.15)

# Checkpointing logic
completed_dense_n = set()
if os.path.exists(dense_csv_path):
    df_dense_chk = pd.read_csv(dense_csv_path)
    completed_dense_n = set(df_dense_chk.groupby('Cohort Size (N)').size()[lambda x: x >= SIM_SEEDS].index)

pending_dense_n = [n for n in dense_sample_sizes if n not in completed_dense_n]

if pending_dense_n:
    for n_size in tqdm(pending_dense_n, desc="Simulating Dense Cohorts"):
        sim_dense_records = []
        for s_idx in range(SIM_SEEDS):
            sim_clf = get_classifier('RandomForest', s_idx)
            X_sample, _, y_sample, _ = train_test_split(X_univ, y_univ, train_size=n_size, random_state=s_idx, stratify=y_univ)
            X_tr, X_te, y_tr, y_te = train_test_split(X_sample, y_sample, test_size=0.20, random_state=s_idx, stratify=y_sample)

            sim_clf.fit(X_tr, y_tr)
            auc_score = roc_auc_score(y_te, sim_clf.predict_proba(X_te)[:, 1])

            sim_dense_records.append({'Cohort Size (N)': n_size, 'Seed': s_idx, 'Test_AUC': auc_score})

        df_dense_chunk = pd.DataFrame(sim_dense_records)
        df_dense_chunk.to_csv(dense_csv_path, mode='a', header=not os.path.exists(dense_csv_path), index=False)
else:
    print("[*] Dense Funnel Simulation already 100% complete.")

"""## Fully Harmonized Factorial Grid"""

# Fully Harmonized Factorial Grid (109 Scenarios)
factorial_csv_path = f"{SIM_DATA_DIR}/Factorial_Structured_Simulation_Results.csv"
print("[*] Compiling Factorial Scenario Matrices...")

raw_scenarios = []
harmonized_n = [50, 75, 100, 150, 200, 300, 500, 1000]

# M1: Sample Size Decay x Imbalance
for n in harmonized_n:
    for imb_tup, imb_name in [((0.5, 0.5), '50/50'), ((0.8, 0.2), '80/20'), ((0.95, 0.05), '95/5')]:
        raw_scenarios.append({'Experiment_Type': 'Sample_Size_x_Imbalance_Surface', 'N_Size': n, 'Features': 15, 'Imbalance': imb_tup, 'Imb_Str': imb_name, 'Noise_Type': 'Boundary', 'Noise_Level': 0.15, 'Split_Ratio': 0.20, 'Class_Sep': 0.8, 'Model_Name': 'RandomForest', 'Do_Repeated_CV': True})

# M2: Dense Imbalance Gradient (N=75)
for imb_tup, imb_name in [((0.95,0.05),'95/5'), ((0.90,0.10),'90/10'), ((0.85,0.15),'85/15'), ((0.80,0.20),'80/20'), ((0.75,0.25),'75/25'), ((0.70,0.30),'70/30'), ((0.65,0.35),'65/35'), ((0.60,0.40),'60/40'), ((0.55,0.45),'55/45'), ((0.50,0.50),'50/50')]:
    raw_scenarios.append({'Experiment_Type': 'Dense_Imbalance_Gradient', 'N_Size': 75, 'Features': 15, 'Imbalance': imb_tup, 'Imb_Str': imb_name, 'Noise_Type': 'Boundary', 'Noise_Level': 0.15, 'Split_Ratio': 0.20, 'Class_Sep': 0.8, 'Model_Name': 'RandomForest', 'Do_Repeated_CV': False})

# M3: Dense Feature Gradient (N=75)
for p in [10, 15, 20, 25, 30, 35, 40, 45, 50]:
    raw_scenarios.append({'Experiment_Type': 'Dense_Feature_Gradient', 'N_Size': 75, 'Features': p, 'Imbalance': (0.8, 0.2), 'Imb_Str': '80/20', 'Noise_Type': 'Boundary', 'Noise_Level': 0.15, 'Split_Ratio': 0.20, 'Class_Sep': 0.8, 'Model_Name': 'RandomForest', 'Do_Repeated_CV': False})

# M4: Signal Separation (N=75)
for sep in [0.4, 0.8, 1.2]:
    raw_scenarios.append({'Experiment_Type': 'Signal_Separation_Sensitivity', 'N_Size': 75, 'Features': 15, 'Imbalance': (0.8, 0.2), 'Imb_Str': '80/20', 'Noise_Type': 'Boundary', 'Noise_Level': 0.15, 'Split_Ratio': 0.20, 'Class_Sep': sep, 'Model_Name': 'RandomForest', 'Do_Repeated_CV': False})

# M5: Model Complexity (N=75, N=300)
for m_name in ['LogisticRegression', 'XGBoost', 'RandomForest']:
    for n in [75, 300]:
        raw_scenarios.append({'Experiment_Type': 'Model_Complexity_Comparison', 'N_Size': n, 'Features': 15, 'Imbalance': (0.8, 0.2), 'Imb_Str': '80/20', 'Noise_Type': 'Boundary', 'Noise_Level': 0.15, 'Split_Ratio': 0.20, 'Class_Sep': 0.8, 'Model_Name': m_name, 'Do_Repeated_CV': True})

# M6: Validation Fraction
for split_val in [0.10, 0.20, 0.30, 0.40, 0.50]:
    raw_scenarios.append({'Experiment_Type': 'Validation_Fraction_Sensitivity', 'N_Size': 75, 'Features': 15, 'Imbalance': (0.8, 0.2), 'Imb_Str': '80/20', 'Noise_Type': 'Boundary', 'Noise_Level': 0.15, 'Split_Ratio': split_val, 'Class_Sep': 0.8, 'Model_Name': 'RandomForest', 'Do_Repeated_CV': False})

# M7: Noise Spectrum
for n_mode in ['Boundary', 'Uniform']:
    for n_lvl in [0.05, 0.10, 0.15, 0.20, 0.25]:
        raw_scenarios.append({'Experiment_Type': 'Noise_Spectrum_Analysis', 'N_Size': 75, 'Features': 15, 'Imbalance': (0.8, 0.2), 'Imb_Str': '80/20', 'Noise_Type': n_mode, 'Noise_Level': n_lvl, 'Split_Ratio': 0.20, 'Class_Sep': 0.8, 'Model_Name': 'RandomForest', 'Do_Repeated_CV': False})

# M8-M12: Harmonized Cross-Interactions
for n in [50, 75, 100, 150, 200, 300, 500]:
    for m_name in ['LogisticRegression', 'XGBoost']: raw_scenarios.append({'Experiment_Type': 'Sample_Size_x_Model_Decay', 'N_Size': n, 'Features': 15, 'Imbalance': (0.8, 0.2), 'Imb_Str': '80/20', 'Noise_Type': 'Boundary', 'Noise_Level': 0.15, 'Split_Ratio': 0.20, 'Class_Sep': 0.8, 'Model_Name': m_name, 'Do_Repeated_CV': True})
    for p in [10, 50]: raw_scenarios.append({'Experiment_Type': 'Dimensionality_x_Sample_Size', 'N_Size': n, 'Features': p, 'Imbalance': (0.8, 0.2), 'Imb_Str': '80/20', 'Noise_Type': 'Boundary', 'Noise_Level': 0.15, 'Split_Ratio': 0.20, 'Class_Sep': 0.8, 'Model_Name': 'RandomForest', 'Do_Repeated_CV': False})
    for n_lvl in [0.05, 0.25]: raw_scenarios.append({'Experiment_Type': 'Noise_x_Sample_Size', 'N_Size': n, 'Features': 15, 'Imbalance': (0.8, 0.2), 'Imb_Str': '80/20', 'Noise_Type': 'Boundary', 'Noise_Level': n_lvl, 'Split_Ratio': 0.20, 'Class_Sep': 0.8, 'Model_Name': 'RandomForest', 'Do_Repeated_CV': False})
    for sep in [0.4, 1.2]: raw_scenarios.append({'Experiment_Type': 'Signal_Separation_x_Sample_Size', 'N_Size': n, 'Features': 15, 'Imbalance': (0.8, 0.2), 'Imb_Str': '80/20', 'Noise_Type': 'Boundary', 'Noise_Level': 0.15, 'Split_Ratio': 0.20, 'Class_Sep': sep, 'Model_Name': 'RandomForest', 'Do_Repeated_CV': False})
for n in [200, 500]:
    for split_val in [0.10, 0.50]: raw_scenarios.append({'Experiment_Type': 'Validation_Fraction_x_Sample_Size', 'N_Size': n, 'Features': 15, 'Imbalance': (0.8, 0.2), 'Imb_Str': '80/20', 'Noise_Type': 'Boundary', 'Noise_Level': 0.15, 'Split_Ratio': split_val, 'Class_Sep': 0.8, 'Model_Name': 'RandomForest', 'Do_Repeated_CV': False})

# Deduplicate
unique_scenarios, seen = [], set()
for sc in raw_scenarios:
    key = (sc['Experiment_Type'], sc['N_Size'], sc['Features'], sc['Imb_Str'], sc['Noise_Type'], sc['Noise_Level'], sc['Split_Ratio'], sc['Class_Sep'], sc['Model_Name'])
    if key not in seen:
        seen.add(key)
        unique_scenarios.append(sc)

EXPLICIT_COLUMNS = ['Experiment_Type', 'N_Size', 'Features_Count', 'Class_Imbalance', 'Noise_Type', 'Noise_Level', 'Split_Ratio', 'Class_Sep', 'Model_Name', 'Seed', 'AUC_Holdout', 'AUC_5Fold_CV', 'AUC_Repeated_CV', 'Brier_Holdout', 'Brier_5Fold_CV', 'Sensitivity_Holdout', 'Sensitivity_5Fold_CV', 'Specificity_Holdout', 'Specificity_5Fold_CV', 'F1_Holdout', 'F1_5Fold_CV']

completed_keys = set()
if os.path.exists(factorial_csv_path):
    df_chk = pd.read_csv(factorial_csv_path)
    grp = df_chk.groupby(['Experiment_Type', 'N_Size', 'Features_Count', 'Class_Imbalance', 'Noise_Type', 'Noise_Level', 'Split_Ratio', 'Class_Sep', 'Model_Name']).size()
    completed_keys = set(grp[grp >= SIM_SEEDS].index.tolist())
else:
    pd.DataFrame(columns=EXPLICIT_COLUMNS).to_csv(factorial_csv_path, index=False)

target_scenarios = [sc for sc in unique_scenarios if (sc['Experiment_Type'], sc['N_Size'], sc['Features'], sc['Imb_Str'], sc['Noise_Type'], sc['Noise_Level'], sc['Split_Ratio'], sc['Class_Sep'], sc['Model_Name']) not in completed_keys]

print(f"[*] Unique Scenarios: {len(unique_scenarios)} | Completed: {len(completed_keys)} | To Execute: {len(target_scenarios)}")

if target_scenarios:
    for exp in tqdm(target_scenarios, desc="Executing Factorial Grid"):
        X_univ, y_univ = make_classification(n_samples=5000, n_features=exp['Features'], n_informative=int(exp['Features']*0.6), n_redundant=int(exp['Features']*0.2), n_clusters_per_class=2, flip_y=0.0, weights=list(exp['Imbalance']), class_sep=exp['Class_Sep'], random_state=42)

        if exp['Noise_Type'] == 'Boundary': y_univ = apply_clinical_boundary_noise(X_univ, y_univ, noise_level=exp['Noise_Level'])
        elif exp['Noise_Type'] == 'Uniform':
            flip_mask = np.random.RandomState(42).rand(len(y_univ)) < exp['Noise_Level']
            y_univ[flip_mask] = 1 - y_univ[flip_mask]

        scenario_records = []
        for s_idx in range(SIM_SEEDS):
            sim_clf = get_classifier(exp['Model_Name'], s_idx)
            X_sample, _, y_sample, _ = train_test_split(X_univ, y_univ, train_size=exp['N_Size'], random_state=s_idx, stratify=y_univ)
            X_tr, X_te, y_tr, y_te = train_test_split(X_sample, y_sample, test_size=exp['Split_Ratio'], random_state=s_idx, stratify=y_sample)

            # Method 1: Holdout
            sim_clf.fit(X_tr, y_tr)
            m_holdout = compute_metrics_bundle(y_te, sim_clf.predict_proba(X_te)[:, 1])

            # Method 2: 5-Fold
            cv_inner = StratifiedKFold(n_splits=5, shuffle=True, random_state=s_idx)
            probs_cv = cross_val_predict(sim_clf, X_sample, y_sample, cv=cv_inner, method='predict_proba', n_jobs=-1)[:, 1]
            m_cv = compute_metrics_bundle(y_sample, probs_cv)

            # Method 3: Repeated 5-Fold (Only if explicitly required to save compute)
            rep_cv_auc = np.nan
            if exp['Do_Repeated_CV']:
                rep_cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=5, random_state=s_idx)
                rep_cv_scores = cross_val_score(sim_clf, X_sample, y_sample, cv=rep_cv, scoring='roc_auc', n_jobs=-1)
                rep_cv_auc = float(np.mean(rep_cv_scores))

            scenario_records.append({
                'Experiment_Type': exp['Experiment_Type'], 'N_Size': exp['N_Size'], 'Features_Count': exp['Features'], 'Class_Imbalance': exp['Imb_Str'], 'Noise_Type': exp['Noise_Type'], 'Noise_Level': exp['Noise_Level'], 'Split_Ratio': exp['Split_Ratio'], 'Class_Sep': exp['Class_Sep'], 'Model_Name': exp['Model_Name'], 'Seed': s_idx,
                'AUC_Holdout': m_holdout['AUC'], 'AUC_5Fold_CV': m_cv['AUC'], 'AUC_Repeated_CV': rep_cv_auc,
                'Brier_Holdout': m_holdout['Brier'], 'Brier_5Fold_CV': m_cv['Brier'],
                'Sensitivity_Holdout': m_holdout['Sens'], 'Sensitivity_5Fold_CV': m_cv['Sens'],
                'Specificity_Holdout': m_holdout['Spec'], 'Specificity_5Fold_CV': m_cv['Spec'],
                'F1_Holdout': m_holdout['F1'], 'F1_5Fold_CV': m_cv['F1']
            })

        pd.DataFrame(scenario_records)[EXPLICIT_COLUMNS].to_csv(factorial_csv_path, mode='a', header=False, index=False)

"""## Publication-Grade In Silico Tables"""

# Publication-Grade In Silico Tables
print("[*] Generating Publication-Grade In Silico Tables...")

df_sim = pd.read_csv(factorial_csv_path)
for c in [col for col in df_sim.columns if 'AUC' in col or 'Brier' in col or 'Sens' in col or 'Spec' in col or 'F1' in col]:
    df_sim[c] = pd.to_numeric(df_sim[c], errors='coerce')

# Global Aggregation (Table S8)
group_keys = ['Experiment_Type', 'N_Size', 'Features_Count', 'Class_Imbalance', 'Noise_Type', 'Noise_Level', 'Split_Ratio', 'Class_Sep', 'Model_Name']
summary_records = []
for key, group in df_sim.groupby(group_keys):
    r = dict(zip(group_keys, key))
    r['Total_Seeds'] = len(group)
    for m in ['Holdout', '5Fold_CV']:
        r[f'{m}_AUC_Mean'] = round(float(group[f'AUC_{m}'].mean()), 3)
        r[f'{m}_AUC_SD'] = round(float(group[f'AUC_{m}'].std()), 3)
        r[f'{m}_Brier_Mean'] = round(float(group[f'Brier_{m}'].mean()), 3)
    r['Repeated_CV_AUC_Mean'] = round(float(group['AUC_Repeated_CV'].mean()), 3) if 'AUC_Repeated_CV' in group and group['AUC_Repeated_CV'].notnull().any() else np.nan
    r['Repeated_CV_AUC_SD'] = round(float(group['AUC_Repeated_CV'].std()), 3) if 'AUC_Repeated_CV' in group and group['AUC_Repeated_CV'].notnull().any() else np.nan
    summary_records.append(r)

df_s8 = pd.DataFrame(summary_records)
df_s8.to_excel(f"{SIM_TABLES_DIR}/Table_S8_Simulation_Master_Summary.xlsx", index=False)

# Table 3: Variance Decay by Sample Size & Imbalance
df_surf = df_sim[df_sim['Experiment_Type'] == 'Sample_Size_x_Imbalance_Surface']
t3_records = []
for (n_val, imb_val), grp in df_surf.groupby(['N_Size', 'Class_Imbalance']):
    h_m, h_s = grp['AUC_Holdout'].mean(), grp['AUC_Holdout'].std()
    cv_m, cv_s = grp['AUC_5Fold_CV'].mean(), grp['AUC_5Fold_CV'].std()
    rep_m, rep_s = grp['AUC_Repeated_CV'].mean(), grp['AUC_Repeated_CV'].std()
    t3_records.append({'Sample Size (N)': int(n_val), 'Prevalence Regime': imb_val, 'Single Holdout AUC': f"{h_m:.3f} (±{h_s:.3f})", '5-Fold CV AUC': f"{cv_m:.3f} (±{cv_s:.3f})", 'Repeated 5-Fold CV AUC': f"{rep_m:.3f} (±{rep_s:.3f})"})
pd.DataFrame(t3_records).sort_values(['Prevalence Regime', 'Sample Size (N)']).to_excel(f"{SIM_TABLES_DIR}/Table_3_Variance_Decay_Methods.xlsx", index=False)

# Support Tables (S3, S4, S5, S6, S7)
anchor_exps = ['Dense_Imbalance_Gradient', 'Dense_Feature_Gradient', 'Signal_Separation_Sensitivity', 'Validation_Fraction_Sensitivity', 'Noise_Spectrum_Analysis']
df_s3_s7 = df_s8[df_s8['Experiment_Type'].isin(anchor_exps)].sort_values(['Experiment_Type', 'Holdout_AUC_SD'])
df_s3_s7.to_excel(f"{SIM_TABLES_DIR}/Table_S3_to_S7_Anchor_Sensitivity_Summaries.xlsx", index=False)

decay_exps = ['Sample_Size_x_Model_Decay', 'Dimensionality_x_Sample_Size', 'Noise_x_Sample_Size', 'Signal_Separation_x_Sample_Size']
df_cross = df_s8[df_s8['Experiment_Type'].isin(decay_exps)].sort_values(['Experiment_Type', 'N_Size'])
df_cross.to_excel(f"{SIM_TABLES_DIR}/Table_S7_Cross_Interactions_Decay.xlsx", index=False)

from scipy.optimize import curve_fit

def power_law(x, a, b): return a * (x ** b)

def interpolate_n(x_data, y_data, target_sd):
    try:
        a, b = curve_fit(power_law, x_data, y_data, maxfev=10000)[0]
        calc_n = (target_sd / a) ** (1 / b)
        return "> 1500" if np.isnan(calc_n) or calc_n > 10000 else f"N ≈ {int(np.round(calc_n / 5) * 5)}"
    except: return "N/A"

p_rows = []
for reg_name, imb_str in {'Balanced (50/50)': '50/50', 'Moderate (80/20)': '80/20', 'Extreme (95/5)': '95/5'}.items():
    df_reg = df_sim[(df_sim['Experiment_Type'] == 'Sample_Size_x_Imbalance_Surface') & (df_sim['Model_Name'] == 'RandomForest') & (df_sim['Class_Imbalance'] == imb_str)]
    for m_name, m_col in {'Single Holdout (80/20)': 'AUC_Holdout', '5-Fold Cross-Validation': 'AUC_5Fold_CV', 'Repeated 5-Fold CV (5x5)': 'AUC_Repeated_CV'}.items():
        sd_data = df_reg.groupby('N_Size')[m_col].std().dropna()
        if len(sd_data) > 3:
            anc_n = 300 if (reg_name == 'Balanced (50/50)' and 'Single' in m_name) else (500 if (reg_name == 'Moderate (80/20)' and 'Single' in m_name) else sd_data.index[-1])
            p_rows.append({
                'Prevalence': reg_name, 'Validation Strategy': m_name,
                'Observed Anchor': f"N = {anc_n} (SD: {sd_data.loc[anc_n] if anc_n in sd_data.index else sd_data.iloc[-1]:.3f})",
                'Criteria 1 (SD <= 0.050)': interpolate_n(sd_data.index.values, sd_data.values, 0.050),
                'Criteria 2 (SD <= 0.025)': interpolate_n(sd_data.index.values, sd_data.values, 0.025)
            })

pd.DataFrame(p_rows).to_csv(f"{SIM_TABLES_DIR}/Table_S2_Interpolated_Sample_Size.csv", index=False)

print("[*] All In Silico Tables successfully exported.")

"""## High-Resolution In Silico Figures"""

# Publication-Grade High-Resolution In Silico Figures
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("[*] Rendering Publication-Grade In Silico Figures (300 DPI)...")

# Directory Configuration
ROOT_DIR = '/content/drive/MyDrive/avc/seed_refatoracao/code'
SIM_DIR = f"{ROOT_DIR}/outputs_v2/simulation"
SIM_DATA_DIR = f"{SIM_DIR}/data"
SIM_FIGS_DIR = f"{SIM_DIR}/figures"
os.makedirs(SIM_FIGS_DIR, exist_ok=True)

# Load Simulation Data
factorial_csv_path = f"{SIM_DATA_DIR}/Factorial_Structured_Simulation_Results.csv"
dense_csv_path = f"{SIM_DATA_DIR}/Dense_Funnel_Simulation_Results.csv"

df_sim = pd.read_csv(factorial_csv_path)
df_dense = pd.read_csv(dense_csv_path)

# Figure 2: Stochastic Convergence, Imbalance Sensitivity, and Variance Decay
fig2 = plt.figure(figsize=(20, 6))
gs = fig2.add_gridspec(1, 3, width_ratios=[1, 1, 1.5])

# Panel (a): Stochastic Convergence
ax1 = fig2.add_subplot(gs[0])
h_vals = df_sim[(df_sim['N_Size'] == 75) & (df_sim['Features_Count'] == 15) &
                (df_sim['Class_Imbalance'] == '80/20') & (df_sim['Model_Name'] == 'RandomForest')].sort_values('Seed')['AUC_Holdout'].dropna().values[:100]
k_rng = np.arange(5, len(h_vals) + 1)
r_mean = [np.mean(h_vals[:k]) for k in k_rng]
r_sem = [np.std(h_vals[:k], ddof=1) / np.sqrt(k) for k in k_rng]

ax1.plot(k_rng, r_mean, color='#1f78b4', lw=2, label='Cumulative Mean AUC')
ax1.fill_between(k_rng, np.array(r_mean) - 1.96*np.array(r_sem), np.array(r_mean) + 1.96*np.array(r_sem), color='#1f78b4', alpha=0.2)
ax1.set_xlabel("Number of Random Seeds Evaluated (Repetitions)", fontsize=10)
ax1.set_ylabel("Running Mean Test AUC-ROC", color='#1f78b4', fontsize=10)
ax1_tw = ax1.twinx()
ax1_tw.plot(k_rng, r_sem, color='#e31a1c', ls='--', lw=2, label='Standard Error (SEM)')
ax1_tw.set_ylabel("Standard Error of the Mean (SEM)", color='#e31a1c', fontsize=10)
ax1.set_title("(a)\nEmpirical Seed Convergence and Precision Stabilization (N=75)", fontweight='bold', pad=15)

# Panel (b): Impact of Event Rarity
ax2 = fig2.add_subplot(gs[1])
df_imb = df_sim[df_sim['Experiment_Type'] == 'Dense_Imbalance_Gradient']
imb_ord = ['95/5', '90/10', '85/15', '80/20', '75/25', '70/30', '65/35', '60/40', '55/45', '50/50']
sns.boxplot(x='Class_Imbalance', y='AUC_Holdout', data=df_imb, order=imb_ord, color='white', showfliers=False, ax=ax2)
sns.stripplot(x='Class_Imbalance', y='AUC_Holdout', data=df_imb, order=imb_ord, color='black', alpha=0.3, size=3, jitter=True, ax=ax2)
ax2.set_xlabel("Class Distribution Ratio (% Negative / % Positive)", fontsize=10)
ax2.set_ylabel("Holdout AUC-ROC", fontsize=10)
ax2.tick_params(axis='x', rotation=45)
ax2.set_title("(b)\nImpact of Event Rarity on Metric Dispersion (Fixed N=75)", fontweight='bold', pad=15)

# Panel (c): Variance Funnel across Sample Sizes
ax3 = fig2.add_subplot(gs[2])
ds_sz = sorted(df_dense['Cohort Size (N)'].unique())
sns.boxplot(x='Cohort Size (N)', y='Test_AUC', data=df_dense, order=ds_sz, color='white', showfliers=False, ax=ax3)
sns.stripplot(x='Cohort Size (N)', y='Test_AUC', data=df_dense, order=ds_sz, color='black', alpha=0.3, size=3, jitter=True, ax=ax3)
g_mean = df_dense['Test_AUC'].mean()
ax3.axhline(g_mean, color='red', ls='--', lw=1.5, alpha=0.7, label=f'Global Mean AUC ({g_mean:.3f})')
ax3.set_xlabel("Cohort Sample Size (N)", fontsize=10)
ax3.set_ylabel("Test Set AUC-ROC", fontsize=10)
ax3.legend(loc='lower right', fontsize=8)
ax3.set_title("(c)\nVariance Funnel Simulation across Incremental Sample Sizes (Step of 25)", fontweight='bold', pad=15)

plt.tight_layout()
plt.savefig(f"{SIM_FIGS_DIR}/Figure_2_Stochastic_Convergence_and_Variance.png", dpi=300, bbox_inches='tight')
plt.close()

# Figure S3: Methodological Variance Funnel (3 Panels)
df_surf = df_sim[df_sim['Experiment_Type'] == 'Sample_Size_x_Imbalance_Surface']
fig3, axes3 = plt.subplots(1, 3, figsize=(18, 5), sharey=True)
for idx, (imb, title) in enumerate([('50/50', '(a)\nBalanced (50/50)'), ('80/20', '(b)\nModerate Imbalance (80/20)'), ('95/5', '(c)\nExtreme Rarity (95/5)')]):
    sd_decay = df_surf[df_surf['Class_Imbalance'] == imb].groupby('N_Size')[['AUC_Holdout', 'AUC_5Fold_CV', 'AUC_Repeated_CV']].std()
    axes3[idx].plot(sd_decay.index, sd_decay['AUC_Holdout'], marker='o', lw=2.2, color='#d95f02', label='Single Holdout (80/20)')
    axes3[idx].plot(sd_decay.index, sd_decay['AUC_5Fold_CV'], marker='s', lw=2.2, color='#7570b3', label='5-Fold Cross-Validation')
    axes3[idx].plot(sd_decay.index, sd_decay['AUC_Repeated_CV'], marker='^', lw=2.2, color='#1b9e77', label='Repeated 5-Fold CV (5x5)')
    axes3[idx].axhline(0.05, color='gray', ls=':', alpha=0.8, label='Precision Stability Threshold (SD <= 0.05)')
    axes3[idx].set_title(title, fontweight='bold', pad=10)
    axes3[idx].set_xlabel("Sample Size (N)")
    axes3[idx].grid(True, ls='--', alpha=0.4)
    if idx == 0: axes3[idx].set_ylabel("AUC-ROC Standard Deviation")
    if idx == 1: axes3[idx].legend(frameon=True, fontsize=9, loc='upper right')

plt.tight_layout()
plt.savefig(f"{SIM_FIGS_DIR}/Figure_S3_Methodological_Variance_Funnel.png", dpi=300, bbox_inches='tight')
plt.close()

# Figure S4: Effect of Feature Dimensionality
fig4, axes4 = plt.subplots(1, 2, figsize=(14, 5))
df_feat = df_sim[df_sim['Experiment_Type'] == 'Dense_Feature_Gradient']
sd_p = df_feat.groupby('Features_Count')['AUC_Holdout'].std().reset_index()
axes4[0].plot(sd_p['Features_Count'], sd_p['AUC_Holdout'], marker='o', lw=2.2, color='#3182bd')
axes4[0].set_title("(a)\nDimensionality and Feature-to-Sample Ratio (p/N at Fixed N=75)", fontweight='bold', pad=10)
axes4[0].set_xlabel("Number of Features (p) [p/N ratio: 0.13 to 0.67]")
axes4[0].set_ylabel("Holdout AUC-ROC Standard Deviation")
axes4[0].grid(True, ls='--', alpha=0.4)

df_dim_decay = df_sim[df_sim['Experiment_Type'] == 'Dimensionality_x_Sample_Size']
for p, col in [(10, '#1b9e77'), (50, '#e7298a')]:
    sd_vals = df_dim_decay[df_dim_decay['Features_Count'] == p].groupby('N_Size')['AUC_Holdout'].std()
    axes4[1].plot(sd_vals.index, sd_vals.values, marker='s', lw=2.2, label=f"Features p={p}", color=col)
axes4[1].set_title("(b)\nDimensionality Interaction across Sample Sizes (p=10 vs p=50)", fontweight='bold', pad=10)
axes4[1].set_xlabel("Sample Size (N)")
axes4[1].legend()
axes4[1].grid(True, ls='--', alpha=0.4)

plt.tight_layout()
plt.savefig(f"{SIM_FIGS_DIR}/Figure_S4_Dimensionality_Impact.png", dpi=300, bbox_inches='tight')
plt.close()

# Figure S5: Effect of Test Set Partition Fraction
df_split = df_sim[df_sim['Experiment_Type'] == 'Validation_Fraction_Sensitivity']
fig5, ax5 = plt.subplots(figsize=(8, 6))
sns.boxplot(x='Split_Ratio', y='AUC_Holdout', data=df_split, color='white', showfliers=False, ax=ax5)
sns.stripplot(x='Split_Ratio', y='AUC_Holdout', data=df_split, color='black', alpha=0.3, size=3, jitter=True, ax=ax5)
ax5.set_title("Validation Fraction Sensitivity on Test Set Metric (Fixed N=75)", fontweight='bold', pad=10)
ax5.set_xlabel("Test Set Proportion (Holdout Fraction)")
ax5.set_ylabel("Holdout AUC-ROC")
ax5.grid(True, ls='--', alpha=0.4)
plt.tight_layout()
plt.savefig(f"{SIM_FIGS_DIR}/Figure_S5_Partition_Fraction_Impact.png", dpi=300, bbox_inches='tight')
plt.close()

# Figure S6: Influence of Label Noise and Task Predictability
fig6, axes6 = plt.subplots(1, 2, figsize=(14, 5))
df_noise = df_sim[df_sim['Experiment_Type'] == 'Noise_x_Sample_Size']
for n_lvl, col, lbl in [(0.05, '#2c7bb6', 'Low Noise (0.05)'), (0.25, '#d7191c', 'High Noise (0.25)')]:
    sd_vals = df_noise[df_noise['Noise_Level'] == n_lvl].groupby('N_Size')['AUC_Holdout'].std()
    axes6[0].plot(sd_vals.index, sd_vals.values, marker='o', lw=2.2, label=lbl, color=col)
axes6[0].set_title("(a)\nSignal-to-Noise Interaction across Sample Sizes", fontweight='bold', pad=10)
axes6[0].set_xlabel("Sample Size (N)"), axes6[0].set_ylabel("Holdout AUC-ROC Standard Deviation")
axes6[0].legend(), axes6[0].grid(True, ls='--', alpha=0.4)

df_sep = df_sim[df_sim['Experiment_Type'] == 'Signal_Separation_x_Sample_Size']
for sep, col, lbl in [(0.4, '#e66101', 'Difficult Task (sep=0.4)'), (1.2, '#5e3c99', 'Easy Task (sep=1.2)')]:
    sd_vals = df_sep[df_sep['Class_Sep'] == sep].groupby('N_Size')['AUC_Holdout'].std()
    axes6[1].plot(sd_vals.index, sd_vals.values, marker='^', lw=2.2, label=lbl, color=col)
axes6[1].set_title("(b)\nTask Predictability Interaction across Sample Sizes", fontweight='bold', pad=10)
axes6[1].set_xlabel("Sample Size (N)")
axes6[1].legend(), axes6[1].grid(True, ls='--', alpha=0.4)

plt.tight_layout()
plt.savefig(f"{SIM_FIGS_DIR}/Figure_S6_Noise_and_Predictability.png", dpi=300, bbox_inches='tight')
plt.close()

# Figure S7: Comparison of Partition Variance across ML Paradigms
fig7, axes7 = plt.subplots(1, 2, figsize=(14, 5))
df_models = df_sim[df_sim['Experiment_Type'] == 'Model_Complexity_Comparison']
sns.boxplot(x='Model_Name', y='AUC_Holdout', hue='N_Size', data=df_models, palette='Blues', showfliers=False, ax=axes7[0])
axes7[0].set_title("(a)\nInductive Bias and Model Paradigm Comparison", fontweight='bold', pad=10)
axes7[0].set_xlabel("Model Architecture"), axes7[0].set_ylabel("Holdout AUC-ROC")
axes7[0].legend(title='Sample Size (N)'), axes7[0].grid(True, ls='--', alpha=0.4)

df_m_decay = df_sim[df_sim['Experiment_Type'].isin(['Sample_Size_x_Model_Decay', 'Sample_Size_x_Imbalance_Surface'])]
df_m_decay = df_m_decay[(df_m_decay['Class_Imbalance'] == '80/20') & (df_m_decay['N_Size'] <= 500)]
for m, col, marker in [('LogisticRegression', '#2b83ba', 'o'), ('XGBoost', '#fdae61', 's'), ('RandomForest', '#d7191c', '^')]:
    sd_vals = df_m_decay[df_m_decay['Model_Name'] == m].groupby('N_Size')['AUC_Holdout'].std()
    axes7[1].plot(sd_vals.index, sd_vals.values, marker=marker, lw=2.2, label=m, color=col)
axes7[1].set_title("(b)\nVariance Decay across Sample Sizes by Model Family (80/20)", fontweight='bold', pad=10)
axes7[1].set_xlabel("Sample Size (N)"), axes7[1].set_ylabel("Holdout AUC-ROC Standard Deviation")
axes7[1].legend(), axes7[1].grid(True, ls='--', alpha=0.4)

plt.tight_layout()
plt.savefig(f"{SIM_FIGS_DIR}/Figure_S7_Model_Paradigms.png", dpi=300, bbox_inches='tight')
plt.close()

print(f"[*] All Publication-Grade Figures successfully exported to: {SIM_FIGS_DIR}")